### ISSUE TITLE
Redundant symbols in "ctex-fontset-pkuthss.def"

### ISSUE THREAD

**Issue by Milozms** [CasperVector/pkuthss#20] opened 2018-12-29 08:15 UTC
In line 39/44/45 there are redundant "[]" symbols, causing compiling errors

**Comment by CasperVector** [comment] 2018-12-29 09:06
I cannot reproduce the issue on my machine with all TeXLive packages updated to the latest releases.
(Using the example template, with `LATEX` set to any of `latex`, `pdflatex` and `xelatex`).

**Comment by CasperVector** [comment] 2018-12-29 09:11
For the reference, if this does happen with certain (version) combinations of package dependencies, it would probably be the result of `fontspec` explicitly forbidding settings like `SomeFont=[simkai.ttf]`, which seems to not yet be the case at least on my machine.

**Comment by CasperVector** [comment] 2019-01-07 09:06
Is the problem still present on your system?
I will close this issue if there is no reply in three days; feel free to reopen it if necessary.

**Closed** 2019-01-10 17:06 UTC
